site_name: Gov Insights
site_description: Documentação da plataforma Gov Insights
site_author: Squad 10
site_url: https://unb-mds.github.io/2025-1-Squad10/
repo_url: https://github.com/unb-mds/2025-1-Squad10
repo_name: GitHub

theme:
  name: material
  language: pt-BR
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: Montserrat
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
    - header.autohide

nav:
  - Início: index.md
  - Sprints:
      - Sprint 0: Sprints/Sprint0.md
      - Sprint 1: Sprints/Sprint01.md
      - Sprint 2: Sprints/Sprint02.md
      - Sprint 3: Sprints/Sprint03.md
      - Sprint 4: Sprints/Sprint04.md
      - Sprint 5: Sprints/Sprint05.md
  - Projeto: Projeto/Projeto.md
  - Como contribuir: Como-contribuir/Como-contribuir.md
  - Sobre: Sobre/Sobre.md

extra_css:
  - assets/extra.css
